name: Run Tests

on: push

jobs:
    test:
        runs-on: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v3
            - run: |
                    python -m venv .venv; \
                    source .venv/bin/activate; \
                    python -m pip install -r requirements.dev.txt; \
                    python -m pytest -vvv tests/
